# Generated by Django 3.0.2 on 2020-02-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryupload',
            name='caption',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='galleryupload',
            name='img_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
