# Generated by Django 3.0.2 on 2020-02-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200210_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryupload',
            old_name='img_title',
            new_name='date',
        ),
    ]
