# Generated by Django 3.0.2 on 2020-02-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='assets')),
                ('desc', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
