# Generated by Django 3.0.2 on 2020-02-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_photoupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoupload',
            old_name='caotion_title',
            new_name='caption_title',
        ),
    ]
