# Generated by Django 3.0.2 on 2020-02-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200210_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Telephone', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=100)),
            ],
        ),
    ]
